### ISSUE TITLE
Why'd you make this a repo?

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [LambdAurora/optifine_alternatives#1]
Why'd you turn your gist into a repo? Is something new coming to this in the future? (Also, I love this list, tysm for it!)

**Comment by LambdAurora** [comment]
The GitHub repo loads *way* faster than the Gist, people can open Pull Requests, if you look at the `data` branch, everything looks more complex, but it kinda makes it easier to edit/add mods, kinda.
And in the future I want to publish a fancier web page with maybe sorting options?

**Comment by BeansBeefBroccoli** [comment]
Ok, cool! Thx for getting back to me so fast. :)

**Comment by BeansBeefBroccoli** [comment]
If I'm understanding this correctly, you're using multiple node.js files to add info about mods (`canvas.mjs`, `okzoomer.mjs`), and then you're putting them together with `build.mjs`, and then finally, you're using Actions to deploy it to Pages, correct?

(sorry I'm still using this issue, but Discussions isn't enabled, so I just decided to talk here)

**Comment by LambdAurora** [comment]
Discussions will be enabled later as I want to use [giscus](https://https://giscus.app/).

And basically, `mod.mjs` in `build_src` will automatically load every files in `alternatives` and one file represents a mod.
`build.mjs` gets all loaded data and build the README.md file, and in the future the HTML pages too.

`./build.sh` can be used to build the rendered version in the `build` directory`.

And yes, a workflow will deploy it to Pages once it's pushed.
