### ISSUE TITLE
Pixelated icons render incorrectly

### ISSUE THREAD

**Issue by haykam821** [LambdAurora/optifine_alternatives#15]
For pixel art icons that are not intrinsically scaled, browsers will resize images with an algorithm designed for large images. This issue can best be seen with the Raised Clouds mod:

<img width="557" alt="Raised Clouds entry with current icon" src="https://user-images.githubusercontent.com/24855774/158904642-a158f571-c2da-48df-9864-1eff9fc79d9e.png">

This effect can be disabled for pixel art icons through the `image-rendering: pixelated;` CSS rule:

<img width="556" alt="Raised Clouds entry with pixelated icon" src="https://user-images.githubusercontent.com/24855774/158904669-5d6737c8-a9be-4831-8f21-39f5b4c48cdc.png">

**Comment by BeansBeefBroccoli** [comment]
Nice
