### ISSUE TITLE
Any new resolution mods?

### ISSUE THREAD

**Issue by danielsmoothie** [LambdAurora/optifine_alternatives#30]
Resolution Control+ hasn't been updated past 1.16.5 (and I don't expect it will because its a fork of an abandoned project). Is there something newer that takes it's place? One of the most useful things about optifine is the AA, which this replaces.

**Comment by BeansBeefBroccoli** [comment]
https://curseforge.com/minecraft/mc-mods/fabrishot

**Comment by meadowsys** [comment]
modrinth page of fabrishot, if you would prefer\
https://modrinth.com/mod/fabrishot
