### ISSUE TITLE
Chime has been updated to 1.19

### ISSUE THREAD

**Issue by intergrav** [LambdAurora/optifine_alternatives#35]
Chime was updated to 1.19, thats all I gotta say
![image](https://user-images.githubusercontent.com/42325132/177603875-ab02d044-b3b8-4e8d-ac58-b49f9ac0de99.png)
![image](https://user-images.githubusercontent.com/42325132/177603915-90b02ce8-1f34-4451-a2bd-488c4b83e35f.png)

**Comment by LambdAurora** [comment]
The Chime entry in the list has been updated.
