### ISSUE TITLE
Vanilla-Friendly Mod to Consider 

### ISSUE THREAD

**Issue by StereoMadnessss** [LambdAurora/optifine_alternatives#45]
This mod, u00a7, allows you to type the § character, which fits into vanilla as a mod that adds functionality.

1.17-1.19.2,
https://www.curseforge.com/minecraft/mc-mods/u00a7
https://modrinth.com/mod/u00a7
https://github.com/NKID00/u00a7

**Comment by LambdAurora** [comment]
I'm not sure this mod fits this list.

I also hope it does not dare to allow the character in the chat as servers will kick when detecting such character!

I also remember being able to paste such characters in books without needing a mod.
