### ISSUE TITLE
Forge (FML) Alternatives/Port of popular Fabric Mods... 

### ISSUE THREAD

**Issue by GamingNerdLeith** [LambdAurora/optifine_alternatives#49]
**Iris Shaders -> Oculus**
Fabric: https://www.curseforge.com/minecraft/mc-mods/irisshaders
Forge: https://www.curseforge.com/minecraft/mc-mods/oculus

**Sodium -> Rubidium**
Fabric: https://www.curseforge.com/minecraft/mc-mods/sodium
Forge: https://www.curseforge.com/minecraft/mc-mods/rubidium

**Sodium Options -> Rubidium Options**
Fabric: https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options
Forge: https://www.curseforge.com/minecraft/mc-mods/textrues-rubidium-options

**Lamb Dynamic Lights -> Magnesium/Rubidium Dynamic Lights**
Fabric: https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights
Forge: https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged

**Sodium Extra -> Magnesium/Rubidium Extras**
Fabric: https://www.curseforge.com/minecraft/mc-mods/sodium-extra
Forge: https://www.curseforge.com/minecraft/mc-mods/magnesium-extras

**Lithium (Fabric) -> Canary or Radium Reforged**
Fabric: https://www.curseforge.com/minecraft/mc-mods/lithium
Forge: https://www.curseforge.com/minecraft/mc-mods/canary
Forge: https://www.curseforge.com/minecraft/mc-mods/radium-reforged

**Phosphor (Fabric) -> Radon or Sulfuric**
Fabric: https://www.curseforge.com/minecraft/mc-mods/phosphor
Forge: https://www.curseforge.com/minecraft/mc-mods/radon
Forge: https://www.curseforge.com/minecraft/mc-mods/phosphor-reforged

**ABC -> ABC**
Fabric: 
Forge:

**Comment by moehreag** [comment]
This had already been asked in the comments discussion, here is the answer: https://github.com/LambdAurora/optifine_alternatives/discussions/2#discussioncomment-2028345

**Comment by BlackAures1** [comment]
> This had already been asked in the comments discussion, here is the answer: [#2 (reply in thread)](https://github.com/LambdAurora/optifine_alternatives/discussions/2#discussioncomment-2028345)

I still don't understand what the problem is with Iris/Oculus. Its developer is Asek3, not CaffeineMC.

**Comment by Gudf** [comment]
> > This had already been asked in the comments discussion, here is the answer: [#2 (reply in thread)](https://github.com/LambdAurora/optifine_alternatives/discussions/2#discussioncomment-2028345)
> 
> I still don't understand what the problem is with Iris/Oculus. Its developer is Asek3, not CaffeineMC.

Actually, according to GH commits authors the main developper for Iris, and therefore Oculus as well albeit indirectly, is currently ISM212 – with coderbot being the original author and most important contributor, and others such as douira having contributed significantly as well – while Asek3 only does pretty much the minimum to have it run of Forge.
Furthermore, while Iris is indeed not a CaffeineMC mod, Oculus arguably suffers from the same issues ports of CaffeineMC mods do: being unofficial and (seemingly) quite low-effort.

**Comment by BlackAures1** [comment]
In this case, are there any other mods for Forge that allow you to use shaders on Curseforge? Because I personally only know Oculus and I haven't had any problems with it.
