### ISSUE TITLE
Missing/broken mod thumbnail for Connected Block Textures

### ISSUE THREAD

**Issue by tehbasshunter** [LambdAurora/optifine_alternatives#74]
Due to discord changing how uploaded media links works it breaks the thumbnail for Connected Block Textures as it does not conform to the format like [this one](https://cdn.discordapp.com/attachments/374635871808520195/1221248152695214211/image.png?ex=6611e2f9&is=65ff6df9&hm=4d689d676fa5b797cbe23583013b62d23ac534d78050884b26e5e6284573ab38&) does.
    
      
![image](https://github.com/LambdAurora/optifine_alternatives/assets/6345556/6a2de95a-c486-4423-985b-c6c473007c86)

**Comment by LambdAurora** [comment]
Discord CDN for attachments now include expiration dates, given that the mod is entirely abandoned anyway it might be best to remove it from the list at this point.
