### ISSUE TITLE
Optifine Not running (Ubuntu) 

### ISSUE THREAD

**Issue by wvandolen** [LambdAurora/optifine_alternatives#79]
Hi. I have an Ubuntu Budgie installation. (And, yes I know that this is not for devs of the real thing) But was wondering if anyone had the same issue or knew how to fix it. Whenever I open Optifine's .jar file, it doesn't open with java or the installer. But instead with file roller, etc. I've tried everything, setting defaults, running commands, and installing java and OpenJDK, etc. When opened in terminal, it shows up as "Unable to access jarfile" I've made sure the file is executable as a program, etc. So please, Any help would be greatly appreciated.

**Comment by LambdAurora** [comment]
This is about alternatives to OptiFine.

This is **not** a help forum for OptiFine-related issues.
