### ISSUE TITLE
Transparent is marked as being available for 1.18, while it is not (1.15 > 1.16 only)

### ISSUE THREAD

**Issue by SpFxx** [LambdAurora/optifine_alternatives#9]
just title

**Comment by LambdAurora** [comment]
This has been already mentioned in https://github.com/LambdAurora/optifine_alternatives/discussions/2#discussioncomment-1804826, but as I said, unless it's confirmed to be actually crashing and not working, it should work as-is.

Sometimes mods can work on versions which are not listed in the compatibility list. Some people have more strict restrictions on versions. This mod is rather simple and has no strict restriction.
